name: mygame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"  # Versão do SDK Flutter compatível com a versão mais recente

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0  # Versão mais recente do bloc
  flutter_bloc: ^8.1.0  # Versão mais recente do flutter_bloc


flutter:
  uses-material-design: true
